### ISSUE TITLE
FeatureRequest: fallback to globally installed gradle

### ISSUE THREAD

**Issue by abendt** [normartin/rust-gradlew-locator#11]
in contrast to gdub this gw fails if it cannot locate a wrapper. gdub in this case falls back to the globally installed gradle.

i think gdubs behaviour makes sense and would think gw should do so too

**Comment by normartin** [comment]
Hey, sounds good. 

Before we can implement that we need to add another feature from gdub. If we want to use a globally installed gradle we need to chose a working directory for it. gdub uses the nearest `build.gradle` or `build.gradle.kt` as an argument if I understand it right. The working directory should probably be where this `build.gradle` file is located, right?

**Comment by abendt** [comment]
yes, that makes sense for me.

to keep in mind:
IMO a good build script should be written in a way that it does not matter what the working directory is. 
If not one could have unexpected results if gw changes the working directory to a different directory where you invoke gw.
