### ISSUE TITLE
feature request: provide windows installer

### ISSUE THREAD

**Issue by abendt** [normartin/rust-gradlew-locator#18]
sometimes i am forced to work in windows environments. It would be nice to have a convenient way to install gw there. Obviously its possible to download the windows binary manually and put it somewhere into the path. 
It would be nice if there was a more convenient way without the need of these manual steps. It would be really nice if it was possible to install it using Chocolatey

**Comment by normartin** [comment]
I get you. But I am not keen on getting into Chocolatey and potentially other package managers. For now I added 4 line Powershell script to the readme that hopefully works for most Windows users (I am not sure about different Windows versions). Be warned that I have zero experience with Powershell :-).

This solution is not ideomatic in a Windows way. Binary is not located where other Windows apps are installed and there is no simple way to uninstall it.

Can you give it try?

https://github.com/normartin/rust-gradlew-locator/tree/windows-installation

**Comment by abendt** [comment]
Worked! Thank you
